/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DentalChartV5RouteImport } from './routes/dental-chart-v5'
import { Route as DentalChartV4RouteImport } from './routes/dental-chart-v4'
import { Route as DentalChartV2RouteImport } from './routes/dental-chart-v2'
import { Route as DentalChartEnhancedRouteImport } from './routes/dental-chart-enhanced'
import { Route as DentalChartRouteImport } from './routes/dental-chart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AuthenticatedTreatmentsRouteImport } from './routes/_authenticated/treatments'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMedicalRecordsRouteImport } from './routes/_authenticated/medical-records'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients/index'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated/users/new'
import { Route as AuthenticatedTasksNewRouteImport } from './routes/_authenticated/tasks/new'
import { Route as AuthenticatedTasksIdRouteImport } from './routes/_authenticated/tasks/$id'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile/edit'
import { Route as AuthenticatedPatientsNewRouteImport } from './routes/_authenticated/patients/new'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated/patients/$id'
import { Route as AuthenticatedUsersIdEditRouteImport } from './routes/_authenticated/users/$id.edit'
import { Route as AuthenticatedPatientsIdEditRouteImport } from './routes/_authenticated/patients/$id.edit'

const DentalChartV5Route = DentalChartV5RouteImport.update({
  id: '/dental-chart-v5',
  path: '/dental-chart-v5',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalChartV4Route = DentalChartV4RouteImport.update({
  id: '/dental-chart-v4',
  path: '/dental-chart-v4',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalChartV2Route = DentalChartV2RouteImport.update({
  id: '/dental-chart-v2',
  path: '/dental-chart-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalChartEnhancedRoute = DentalChartEnhancedRouteImport.update({
  id: '/dental-chart-enhanced',
  path: '/dental-chart-enhanced',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalChartRoute = DentalChartRouteImport.update({
  id: '/dental-chart',
  path: '/dental-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTreatmentsRoute = AuthenticatedTreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedicalRecordsRoute =
  AuthenticatedMedicalRecordsRouteImport.update({
    id: '/medical-records',
    path: '/medical-records',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksNewRoute = AuthenticatedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksIdRoute = AuthenticatedTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsNewRoute =
  AuthenticatedPatientsNewRouteImport.update({
    id: '/patients/new',
    path: '/patients/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIdEditRoute =
  AuthenticatedUsersIdEditRouteImport.update({
    id: '/users/$id/edit',
    path: '/users/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsIdEditRoute =
  AuthenticatedPatientsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPatientsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dental-chart': typeof DentalChartRoute
  '/dental-chart-enhanced': typeof DentalChartEnhancedRoute
  '/dental-chart-v2': typeof DentalChartV2Route
  '/dental-chart-v4': typeof DentalChartV4Route
  '/dental-chart-v5': typeof DentalChartV5Route
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/medical-records': typeof AuthenticatedMedicalRecordsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/treatments': typeof AuthenticatedTreatmentsRoute
  '/docs': typeof DocsIndexRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRouteWithChildren
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/patients/$id/edit': typeof AuthenticatedPatientsIdEditRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dental-chart': typeof DentalChartRoute
  '/dental-chart-enhanced': typeof DentalChartEnhancedRoute
  '/dental-chart-v2': typeof DentalChartV2Route
  '/dental-chart-v4': typeof DentalChartV4Route
  '/dental-chart-v5': typeof DentalChartV5Route
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/medical-records': typeof AuthenticatedMedicalRecordsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/treatments': typeof AuthenticatedTreatmentsRoute
  '/docs': typeof DocsIndexRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRouteWithChildren
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/patients/$id/edit': typeof AuthenticatedPatientsIdEditRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/dental-chart': typeof DentalChartRoute
  '/dental-chart-enhanced': typeof DentalChartEnhancedRoute
  '/dental-chart-v2': typeof DentalChartV2Route
  '/dental-chart-v4': typeof DentalChartV4Route
  '/dental-chart-v5': typeof DentalChartV5Route
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/medical-records': typeof AuthenticatedMedicalRecordsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/treatments': typeof AuthenticatedTreatmentsRoute
  '/docs/': typeof DocsIndexRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRouteWithChildren
  '/_authenticated/patients/new': typeof AuthenticatedPatientsNewRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/_authenticated/tasks/new': typeof AuthenticatedTasksNewRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/patients/$id/edit': typeof AuthenticatedPatientsIdEditRoute
  '/_authenticated/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dental-chart'
    | '/dental-chart-enhanced'
    | '/dental-chart-v2'
    | '/dental-chart-v4'
    | '/dental-chart-v5'
    | '/login'
    | '/signup'
    | '/appointments'
    | '/billing'
    | '/dashboard'
    | '/medical-records'
    | '/reports'
    | '/settings'
    | '/treatments'
    | '/docs'
    | '/patients/$id'
    | '/patients/new'
    | '/profile/edit'
    | '/tasks/$id'
    | '/tasks/new'
    | '/users/new'
    | '/patients'
    | '/profile'
    | '/tasks'
    | '/users'
    | '/patients/$id/edit'
    | '/users/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dental-chart'
    | '/dental-chart-enhanced'
    | '/dental-chart-v2'
    | '/dental-chart-v4'
    | '/dental-chart-v5'
    | '/login'
    | '/signup'
    | '/appointments'
    | '/billing'
    | '/dashboard'
    | '/medical-records'
    | '/reports'
    | '/settings'
    | '/treatments'
    | '/docs'
    | '/patients/$id'
    | '/patients/new'
    | '/profile/edit'
    | '/tasks/$id'
    | '/tasks/new'
    | '/users/new'
    | '/patients'
    | '/profile'
    | '/tasks'
    | '/users'
    | '/patients/$id/edit'
    | '/users/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/dental-chart'
    | '/dental-chart-enhanced'
    | '/dental-chart-v2'
    | '/dental-chart-v4'
    | '/dental-chart-v5'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authenticated/appointments'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/medical-records'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/treatments'
    | '/docs/'
    | '/_authenticated/patients/$id'
    | '/_authenticated/patients/new'
    | '/_authenticated/profile/edit'
    | '/_authenticated/tasks/$id'
    | '/_authenticated/tasks/new'
    | '/_authenticated/users/new'
    | '/_authenticated/patients/'
    | '/_authenticated/profile/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/patients/$id/edit'
    | '/_authenticated/users/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  DentalChartRoute: typeof DentalChartRoute
  DentalChartEnhancedRoute: typeof DentalChartEnhancedRoute
  DentalChartV2Route: typeof DentalChartV2Route
  DentalChartV4Route: typeof DentalChartV4Route
  DentalChartV5Route: typeof DentalChartV5Route
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/dental-chart-v5': {
      id: '/dental-chart-v5'
      path: '/dental-chart-v5'
      fullPath: '/dental-chart-v5'
      preLoaderRoute: typeof DentalChartV5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-chart-v4': {
      id: '/dental-chart-v4'
      path: '/dental-chart-v4'
      fullPath: '/dental-chart-v4'
      preLoaderRoute: typeof DentalChartV4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-chart-v2': {
      id: '/dental-chart-v2'
      path: '/dental-chart-v2'
      fullPath: '/dental-chart-v2'
      preLoaderRoute: typeof DentalChartV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-chart-enhanced': {
      id: '/dental-chart-enhanced'
      path: '/dental-chart-enhanced'
      fullPath: '/dental-chart-enhanced'
      preLoaderRoute: typeof DentalChartEnhancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-chart': {
      id: '/dental-chart'
      path: '/dental-chart'
      fullPath: '/dental-chart'
      preLoaderRoute: typeof DentalChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/treatments': {
      id: '/_authenticated/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof AuthenticatedTreatmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medical-records': {
      id: '/_authenticated/medical-records'
      path: '/medical-records'
      fullPath: '/medical-records'
      preLoaderRoute: typeof AuthenticatedMedicalRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/new': {
      id: '/_authenticated/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthenticatedTasksNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/$id': {
      id: '/_authenticated/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AuthenticatedTasksIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/new': {
      id: '/_authenticated/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthenticatedPatientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id/edit': {
      id: '/_authenticated/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof AuthenticatedUsersIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$id/edit': {
      id: '/_authenticated/patients/$id/edit'
      path: '/edit'
      fullPath: '/patients/$id/edit'
      preLoaderRoute: typeof AuthenticatedPatientsIdEditRouteImport
      parentRoute: typeof AuthenticatedPatientsIdRoute
    }
  }
}

interface AuthenticatedPatientsIdRouteChildren {
  AuthenticatedPatientsIdEditRoute: typeof AuthenticatedPatientsIdEditRoute
}

const AuthenticatedPatientsIdRouteChildren: AuthenticatedPatientsIdRouteChildren =
  {
    AuthenticatedPatientsIdEditRoute: AuthenticatedPatientsIdEditRoute,
  }

const AuthenticatedPatientsIdRouteWithChildren =
  AuthenticatedPatientsIdRoute._addFileChildren(
    AuthenticatedPatientsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMedicalRecordsRoute: typeof AuthenticatedMedicalRecordsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTreatmentsRoute: typeof AuthenticatedTreatmentsRoute
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRouteWithChildren
  AuthenticatedPatientsNewRoute: typeof AuthenticatedPatientsNewRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedTasksIdRoute: typeof AuthenticatedTasksIdRoute
  AuthenticatedTasksNewRoute: typeof AuthenticatedTasksNewRoute
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedUsersIdEditRoute: typeof AuthenticatedUsersIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMedicalRecordsRoute: AuthenticatedMedicalRecordsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTreatmentsRoute: AuthenticatedTreatmentsRoute,
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRouteWithChildren,
  AuthenticatedPatientsNewRoute: AuthenticatedPatientsNewRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedTasksIdRoute: AuthenticatedTasksIdRoute,
  AuthenticatedTasksNewRoute: AuthenticatedTasksNewRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedUsersIdEditRoute: AuthenticatedUsersIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  DentalChartRoute: DentalChartRoute,
  DentalChartEnhancedRoute: DentalChartEnhancedRoute,
  DentalChartV2Route: DentalChartV2Route,
  DentalChartV4Route: DentalChartV4Route,
  DentalChartV5Route: DentalChartV5Route,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
